name: Build Application

on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags: ["v*.*.*"]

  pull_request:
    branches:
      - master
      - developed
      - feature/*
      - test/*
      - hotfix/*
      - fix/*
      - tech/
    types: [opened, synchronize, closed]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  IS_MERGED: ${{ github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged }}

jobs:
  update-tag-version:
    name: Generate semantic version Tag
    if: ${{ github.event.action != 'closed' }}
    uses: ./.github/workflows/update_semver.yml

  build-api:
    needs: [update-tag-version]
    name: Build API
    runs-on: ubuntu-latest
    outputs:
      last_tag: ${{ steps.last_tag.outputs.TARGET_TAG }}
      pr_number: ${{ steps.findPr.outputs.pr }}
    defaults:
      run:
        working-directory: .

    steps:
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "9.0.x"

      - name: Setup Reviewdog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: "v0.20.3"

      - name: Run StyleCop with Reviewdog
        run: |
          dotnet format --severity info | reviewdog -efm="%f(%l,%c): %m" -name="StyleCop" -reporter=github-pr-review
        continue-on-error: true

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache SonarCloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v3
        with:
          path: ./.sonar/scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner

      - name: Find Current PR
        uses: jwalton/gh-find-current-pr@v1
        id: findPr
        with:
          state: open

      - name: Get PR Number
        run: echo "Your PR is ${PR}"
        if: success() && steps.findPr.outputs.number
        env:
          PR: ${{ steps.findPr.outputs.pr }}

      - name: Get Last Git Tag
        id: last_tag
        shell: bash
        run: |
          tag_v=$(git describe --tags $(git rev-list --tags --max-count=1))
          tag=$(echo $tag_v | sed 's/v//')

          echo "TARGET_TAG=${tag}" >> $GITHUB_OUTPUT
          echo "Last git tag: $tag"

      - name: Install Quality Tools
        shell: bash
        run: |
          dotnet tool install --global JetBrains.dotCover.GlobalTool --version 2023.2.3
          dotnet tool install --global dotnet-sonarscanner --version 5.14.0

      - name: Make the scanner script file executable
        run: |
          chmod +x ./startsonar.sh

      - name: Start sonar scanning
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ env.SONAR_TOKEN }}
          GITHUB_RUN_ID: ${{ github.run_id }}
          RUN_NUMBER: ${{ github.run_number }}
          RUN_ATTEMPT: ${{ github.run_attempt }}
          PULL_REQUEST_ID: ${{ steps.findPr.outputs.pr }}
          PULL_REQUEST_SOURCE_BRANCH: ${{ github.ref }}
          PULL_REQUEST_TARGET_BRANCH: refs/heads/master
          ACTION: ${{ github.action }}
          EVENT_NAME: ${{ github.event_name }}
        shell: bash
        run: sh ./startsonar.sh

      - name: Build Solution for Metrics
        shell: bash
        run: |
          dotnet build HomeBudgetAccountingApi.sln --no-incremental

      - name: Run Tests with Coverage
        shell: bash
        run: |
          dotnet-dotcover test HomeBudgetAccountingApi.sln \
            --dcReportType=HTML \
            --dcOutput="test-results/accounting-coverage.html" \
            --dcFilters="+:HomeBudget.*;-:type=*.IntegrationTests;-:type=*.Tests"
        continue-on-error: true
        timeout-minutes: 15

      - name: End sonar scanning
        env:
          SONAR_TOKEN: ${{ env.SONAR_TOKEN }}
        shell: bash
        run: dotnet-sonarscanner end /d:sonar.token="${{ env.SONAR_TOKEN }}"

  build-docker:
    name: Build and Push Docker Image
    needs: [build-api]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build Docker Image
        env:
          BUILD_VERSION: ${{ needs.build-api.outputs.last_tag }}
        shell: bash
        run: |
          docker build \
            --target 'final' \
            -t "${{ secrets.DOCKERHUB_USERNAME }}/homebudget-accounting-api:${{ needs.build-api.outputs.last_tag }}" \
            .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker Image
        shell: bash
        run: |
          docker push "${{ secrets.DOCKERHUB_USERNAME }}/homebudget-accounting-api:${{ needs.build-api.outputs.last_tag }}"
